### ISSUE TITLE
Citation for using this

### ISSUE THREAD

**Issue by CornelisB** [anastasia-lucas/hudson#10]
Hi, thanks for this! this is so cool and easy to use!
Is there any citation you want me to include when using this package for a figure in a publication?
Thanks!

**Comment by anastasia-lucas** [comment]
Hi! Thanks for using the package and appreciate the comments. 
I think the "standard" R citation format would work, in this case:

Anastasia Lucas (2020). hudson: An R package for creating mirrored Manhattan plots. R package version 0.1.0.

I will work on adding a friendlier `citation("hudson")` output this weekend.
