### ISSUE TITLE
Suggest: remove limit on the number of chromosomes

### ISSUE THREAD

**Issue by richelbilderbeek** [anastasia-lucas/hudson#12]
Hi @anastasia-lucas,

I work on GWAS data with more chomosomes than humans have. When using hudson to plot this, it looks like this:

![Screenshot from 2021-06-17 13-43-14](https://user-images.githubusercontent.com/2098230/122390188-00b4c380-cf72-11eb-8803-e598d722d7e8.png)

I expected no limit on the number of chromosomes and thus expected to see a full plot.

If you want, I'd be happy to create a reprex.

**Comment by anastasia-lucas** [comment]
Hi, Richel. Thanks, this is a great suggestion. Would it work if I create an argument that allows you to override the default with an ordered list of your chromosomes?

**Comment by richelbilderbeek** [comment]
Hi @anastasia-lucas, thanks for your fun reaction! 

I suggest to do what you already do, which is to extract the chromosome numbers from the data (i.e. -as far as I remember- the `chr` field). In that way, users with a high chromosome number get a complete plot with the same code as those users that work on humans :-)

You'd think you could get that to work?

Thanks and cheers, Richel

**Comment by anastasia-lucas** [comment]
Hi @richelbilderbeek, while I agree that it would be most convenient to auto-extract the chromosomes from the data, there can be issues with deciding the order they appear on the plot when a user has a mix of numeric and character values.

I have now updated the package with a `chroms` argument in the `gmirror()` and `phemirror()` functions which now will take a list, in order, of the chromosomes you wish to plot. By default, `chroms=c(1:22, "X",  "Y")` but you should be able to easily change to the dog genome, for example, by adding `chroms=1:39` to the function call.

The addition of this argument has a few benefits as it will allow you to specify to plot only chromosomes of interest and will allow for non-standard chromosomes names such as "MT" and "XY."

Hope this will be helpful for your work.

**Comment by richelbilderbeek** [comment]
Yup, that works like a breeze, thanks @anastasia-lucas! 

As a reminder to self, here is a reprex and figure:

```r
  t <- tidyr::expand_grid(
    CHR = seq(1, 30),
    POS = seq(1, 10)
  )
  t$pvalue = runif(n = 300)
  t$SNP = seq(1, 300)
  hudson::gmirror(
    top = t,
    bottom = t,
    chroms = 1:30
  )
```

![gmirror](https://user-images.githubusercontent.com/2098230/123038267-5b29a600-d3f0-11eb-8c51-292920d2051f.png)
