### ISSUE TITLE
freey option yielding strange results / add support for differing y-axis dimensions 

### ISSUE THREAD

**Issue by skhenne** [anastasia-lucas/hudson#8]
I'm facing some issues with gmirror when trying to plot datasets with very different y-axis limits (one should be around -300, the other -7). I tried `freey=TRUE`, but this did not have the effect I expected - the bottom plot looked fine with an ylimit of around -7, while the top plot seemed to not have any data plotted, only showing flat lines for the chromosomes and threshold and no y axis labels.

**Comment by anastasia-lucas** [comment]
Would you be able to post a reproducible example so I can look into it? Thanks!

**Comment by anastasia-lucas** [comment]
Closing this issue for now. I can reopen if there are any additional comments
