### ISSUE TITLE
set different p-value cut-off for upper and bottom

### ISSUE THREAD

**Issue by Shicheng-Guo** [anastasia-lucas/hudson#9]
Hi Anastasia, 

How to set different p-value cut-off for upper and bottom panel to show significant SNPs.

Thanks. 

Shicheng

**Comment by anastasia-lucas** [comment]
Hi. If you are referring to the annotation and highlight thresholds, you can supply the function with a list of p-values in the order of upper panel p-value and bottom panel p-value ex. `highlight_p=c(p_top, p_bottom)` 
This should work for `highlight_p` and `annotate_p`. 
Please let me know if your question was referring to something else.
